<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />	
    <title>User Login</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />    
</head>

<body>
	<div class="container">
	<div class="row">
	    <div class="col-md-6 col-md-offset-3">
			<h1>User Login</h1>
			<form method="POST" action="/login">
				<input type="hidden" name="<?= $nameKey ?>" value="<?= $name ?>">
				<input type="hidden" name="<?= $valueKey ?>" value="<?= $value ?>">   
				<div class="form-group">
					<label for="exampleInputEmail1">Email address</label>
					<input type="email" class="form-control" id="exampleInputEmail1" name="email" placeholder="Email" required>
				</div>
				<div class="form-group">
					<label for="exampleInputPassword1">Password</label>
					<input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password" required>
				</div>   
			  <button type="submit" class="btn btn-default">Submit</button>
			</form>	        	       
	    </div>	
    </div>	
    </div>	

</body>

<script
  src="http://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</html>
