<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />	
    <title>User Signup</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />    
</head>

<body>
	<div class="container">
	<div class="row">
	    <div class="col-md-6 col-md-offset-3">
			<h1>User Signup</h1>
			<form method="POST" action="/signup">
				<input type="hidden" name="<?= $nameKey ?>" value="<?= $name ?>">
				<input type="hidden" name="<?= $valueKey ?>" value="<?= $value ?>">   
				
				<div class="form-group">
					<label for="username">Name</label>
					<input name="name" type="text" class="form-control" id="username" placeholder="Name" required>
				</div>	
				<div class="form-group">
					<label for="age">Age</label>
					<input name="age" type="number" min="18" max="99" class="form-control" id="age" placeholder="Age" required>
				</div>	
				<div class="form-group">
					<div class="radio">
					  <label>
					    <input type="radio" name="gender" id="optionsRadios1" value="M" checked>
					    Male
					  </label>
					</div>
					<div class="radio">
					  <label>
					    <input type="radio" name="gender" id="optionsRadios2" value="F">
					    Female
					  </label>
					</div>
				</div>	
				<div class="form-group">
					<label for="country">country</label>
					<input name="country" type="text" class="form-control" id="country" placeholder="country" required>
				</div>	
				<div class="form-group">
					<label for="exampleInputEmail1">Email address</label>
					<input name="email" type="email" class="form-control" id="exampleInputEmail1" placeholder="Email" required>
				</div>
				<div class="form-group">
					<label for="exampleInputPassword1">Password</label>
					<input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" required>
				</div>   
			  <button type="submit" class="btn btn-default">Submit</button>
			</form>			
	    </div>	
    </div>	
    </div>	

</body>

<script
  src="http://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</html>